### ISSUE TITLE
Transition mass and input yield grid

### ISSUE THREAD

**Issue by chritter** [NuGrid/NuPyCEE#13]
When the transitionmass variable is set to one of the input yield grid masses then the initial mass range intervals for the yields are not set properly. Visible with iolevel=1. To solve this need to decide how the initial mass range intervals are split up in such a case.

**Comment by becot85** [comment]
Hi Christian.  Yes that is a valid concern.  In this case, maybe we could simply set the real transitionmass (the one used in the code) to 0.9999transitionmass?  This should not change the final results significantly.  In the case the transition mass is equal to the highest mass available in the yields, we could set the real transitionmass to 1.0001transitionmass (although this will probably never happen..).  What do you think?
