### ISSUE TITLE
Extra sources flexibility

### ISSUE THREAD

**Issue by becot85** [NuGrid/NuPyCEE#14]
I think a good modification to our codes would be to add a mass range associated with the extra_source_table.  Furthermore, it would be great to convert these parameters into arrays where the index of these array refers to one specific extra source.  Here is an example with 2 extra sources:

extra_mass_range = [ [1,8], [8,12] ] 
extra_source_table = ['s-process table.txt', 'r-process table.txt']

That would allow to control in which stars the extra table is applied, and it would prevent from adding more and more parameters for additional extra sources.  In chem_evol.py, we could simply loop over the length of the extra_mass_range array.

I think we could do the same for delayed sources that need a delay time (e.g., neutron star mergers, black hole neutron star mergers, iRAWDs, and other things we want to try). We would "simply" need to include a delay-time distribution array as well.

**Comment by chritter** [comment]
I agree there is a lot of potential! I have added the capability for extra sources.
See https://github.com/NuGrid/NuPyCEE/blob/master/Teaching/ExtraSources.ipynb
