### ISSUE TITLE
WENDI interface-This site can’t be reached

### ISSUE THREAD

**Issue by juzikong** [NuGrid/NuPyCEE#21]
https://nugrid.github.ioprojects/wendi
nugrid.github.ioprojects’s server IP address could not be found.

**Comment by becot85** [comment]
Thank you for reporting this. The WENDI server status can be seen on the NuGrid website (https://nugrid.github.io/content/wendi). However, we are now solving a few things on WENDI, hopefully the server will be back online soon. I will keep you up-to-date.
