### ISSUE TITLE
Bugs of ry

### ISSUE THREAD

**Issue by JinningLianggithub** [NuGrid/NuPyCEE#40]
When I use the function to read the yields table, it shows that there is no ry. I check the code from NuPyCEE, there is no definition of ry. However, it use it and its function to read the table. Obviously, it cannot work.

**Comment by becot85** [comment]
Thanks for reaching out. 

"ry" is defined in NuPyCEE in chem_evol.py (import NuPyCEE.read_yields as ry). If you look further into chem_evol.py, you will see that NuPyCEE calls the classes "ry.read_yields_Z(...)" and "ry.read_yields_M_Z(...)". These two classes inherit from the class "ry.read_yields(...)".

If you want to read yields tables by your own, without using the chemical evolution codes (i.e. SYGMA or OMEGA), you need to import NuPyCEE.read_yields as ry, and then either use ry.read_yields_Z or ry.read_yields_M_Z, depending on whether your yields are metallicity-dependent only, or mass- and metallicity-dependent. 

If you encounter a problem, or have questions, please let me know.  If I did not understand properly your issue, could you please provide more details so I can reproduce the problem?

Have a nice day.

**Comment by JinningLianggithub** [comment]
Dear Benoit Côté

Thanks for your help!
I've been busy these days and I just found that you have sent this
email. Sorry for replying late. Now, I can run the ry correctly. If I
encounter any problem later, I will let you know.
Thanks for your patience! That's very kind of you.

Best regards,
Jinning Liang


Benoit Côté ***@***.***> 于2021年6月30日周三 下午11:45写道：

**Comment by becot85** [comment]
Dear Jinning,

No worries, thanks for letting me know! Please reach out to me if you encounter any problem.

Have a nice day,
Benoit
