### ISSUE TITLE
chem_evol.py -> comma missing between two elements in an array

### ISSUE THREAD

**Issue by stormnick** [NuGrid/NuPyCEE#44]
chem_evol.py, line 1563, definition of "self.elem_list_periodic_table". There is a comma missing between elements "Rn" "Fr", thus causing those two elements to combine together into one "RnFr". This cases self.elem_list_periodic_table to incorrectly have corresponding element number after Rn (86th element). Adding a comma solves the issue.

**Comment by becot85** [comment]
Thanks a lot! I made the adjustment and pushed the change directly to the master branch. Have a nice day.
